
export const projects = [
  {
    title: 'Dev Chat',
    description: "This app will allow users to create chat channels. You can direct message other people. You can respond as normal or add a gif/image and even be able to use emjoi's. If a user signs up and adds their cell number, they can receive text notifications as well.",
      image: '/images/chat.PNG',
      tags: ['React', 'Express', 'Node'],
    source: 'https://github.com/ericcapiz/chat',
    visit: 'https://devs-chat.netlify.app/',
    id: 12,
  },
  {
    title: 'Sigma Snap',
    description: "This app will allow users to register/log-in and upload a post that will contain an image, title, message and tags. Each post will render the users name and display how long ago the post was created.",
      image: '/images/snaps.PNG',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/ericcapiz/Sigma-Snaps',
    visit: 'https://sigma-snaps.netlify.app/',
    id: 0,
  },
  {
    title: 'Lost My Stuff',
    description: "A lost and found site for users to create posts for items lost or found. This is a MERN application that allows users to register/login and create posts for items. Users can update/delete their own posts. Users can display posts by category as well as by user if user has multiple posts.",
      image: '/images/lost.PNG',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/ericcapiz/lost-found',
    visit: 'https://lost-my-stuff.vercel.app/',
    id: 2,
  },
  {
    title: 'Food 4 Thought',
    description: "This app will allow users to search for ingredients and view different recipe cards for additional recipe info.",
      image: '/images/food.PNG',
      tags: ['React', 'State Management', 'Styled Components'],
    source: 'https://github.com/ericcapiz/food-4-thought',
    visit: 'https://food-4-thought.vercel.app/',
    id: 8,
  },
  {
    title: 'Psi-Shop',
    description:"This app will allow users to add items to their cart. Once in the cart users can increase/decrease quantity of items in the cart. Users can also remove the item or even empty the cart altogether.",
    image: '/images/psi.PNG',
    tags: ['React', 'Commerce.js', 'Stripe'],
    source: 'https://github.com/ericcapiz/psi-shop',
    visit: 'https://psi-shop.netlify.app/',
    id: 1,
  },
  {
    title: 'Zeta Movies',
    description: "This app will allow users to search for any movie and can click on any movie listed to view the movie card for additional info on the movie",
    image: '/images/zeta1.PNG',
    tags: ['React', 'Styled Components', 'State Management'],
    source: 'https://github.com/ericcapiz/zeta-movies',
    visit: 'https://zeta-movies.vercel.app/',
    id: 3,
  },

  {
    title: 'Covid Tracker',
    description: "This app uses the disease.sh api. This gives data that shows users the different numbers worldwide and by country. The numbers update as the api updates.",
    image: '/images/covid.PNG',
    tags: ['React', 'Chart.js', 'Leaflet'],
    source: 'https://github.com/ericcapiz/covid',
    visit: 'https://covid-vert-zeta.vercel.app/',
    id: 4,
  },
  {
    title: 'Nandos Cakes',
    description: "I developed this site for a chicago start-up bakery business. They have a fb channel with over 350 followers and I offered my services to help market the business by creating their site.",
    image: '/images/cake.PNG',
    tags: ['React', 'Email.js', 'Framer-Motion'],
    source: 'https://github.com/ericcapiz/nandos-cakes2',
    visit: 'https://nandos-cakes2.vercel.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2014, text: 'Graduated from Devry University with a bachelors degree in multimedia design & development', },
  { year: 2019, text: 'Decided to get back into the web dev field and start the self-taught path', },
  { year: 2020, text: 'Started Lambda School in their fullstack development program', },
  { year: 2021, text: 'Became a freelance developer', },
];